# Generated by Django 3.2 on 2021-05-16 05:22

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_auto_20210514_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[utils.validators.validate_phone_number]),
        ),
    ]
