# Generated by Django 3.2 on 2021-05-16 05:22

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210514_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, validators=[utils.validators.validate_discount], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='src',
            field=models.ImageField(upload_to=utils.upload.product_images_directory_path, validators=[utils.validators.validate_size, utils.validators.validate_extension]),
        ),
    ]
