# Generated by Django 3.2 on 2021-05-16 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210516_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='duration',
        ),
        migrations.AddField(
            model_name='promotion',
            name='finish_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Конец акции'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Начало акции'),
        ),
    ]
